serial_port="/dev/ttyUSB-P1"
interval=15
url="192.168.2.1:8086"
username="yage"
password="deltamk2"
database="energy"
token="atjhxQljTjxawH2gWT7fquz0sEaYekgGSIiENddzwlACo4xsJ18DpbuqzhlDWoyQvGlgXxkWF63-yViFxuWJiw=="
bucket="homebucket"
org="home"
